### PR TITLE
S4Data rename to xData in DataRepresentable

### PR DESCRIPTION
**Pull request by dreymonde**

### CODE REVIEW

**Comment by tanner0101** [comment]
What is the reasoning for this?

**Comment by dreymonde** [comment]
@tannernelson well, two reasons now:
1) S4Data has no sense since it’s now in C7 repo :)
2) Swift API guidelines forbid naming functions/parameters with uppercase at the beginning:

> Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions:
> 
> ``` swift
> var utf8Bytes: [UTF8.CodeUnit];
> var isRepresentableAsASCII = true;
> var userSMTPServer: SecureSMTPServer;
> ```

**Comment by tanner0101** [comment]
Oh so `x` is like Swift **X** ?

**Comment by dreymonde** [comment]
Yes, exactly. There was a short discussion about that in Slack.

**Pull request merged**
