### PR TITLE
Make JSON Equatable

### PR DESCRIPTION
**Pull request by czechboy0**
Just makes JSON Equatable (do we need to wait a week to merge even technical fixes/small improvements @tannernelson?)

### CODE REVIEW

**Comment by loganwright** [comment]
This would affect our current implementation of Json equality which is a bit fuzzier than perhaps it should be. We treat number more abstract where if one is a number type Integer, and the other is type Double, they still match. This is done to alleviate some of the uncertainty of how its being parsed. I'm not saying everyone should implement this type of equality, but it would break our implementation in a way that I'd prefer to avoid. I'd like to discuss either not including this, or making a fuzzier equality at least within the JSON.Number to accommodate less specific serializations. ie: Json.number(1.0) should equal parsed number Json.number(1)

**Comment by paulofaria** [comment]
I think JSON numbers should be compared regardless of how they're stored. How they're stored is an implementation detail that is only related with range and precision. In effect, `1`, `1.0` and `1E0` are all the same JSON number. So I agree with @LoganWright about the regular `==` implementation. @czechboy0 if you need an equality check that takes into account the storage type it should be a different function.

**Comment by czechboy0** [comment]
Okay, but as I'm not sure how to do what you guys want to do well, I'll welcome a PR into my branch which changes it, aight?

**Comment by czechboy0** [comment]
My problem with that is comparing floating point numbers is not easy, and if you want to suddenly compare an Int with a Double, how do you do that? Once you cast Int into a Double it suddenly is a different number. So I'll be happy to be proven wrong if you have a way to solve this 👍

**Comment by paulofaria** [comment]
@LoganWright have a link to your's implementation?

**Comment by loganwright** [comment]
@czechboy0 @paulofaria I made a pr here to check, we can merge it into this one if we like it #42 to treat it as one proposal

**Comment by czechboy0** [comment]
@LoganWright @paulofaria Thanks guys, I made some final esthetic tweaks. /cc @open-swift/contributors Please chime in.

**Comment by czechboy0** [comment]
Actually, @LoganWright could you make those conversions public? I don't see why they shouldn't be (I'd definitely use them in certain cases).

**Comment by paulofaria** [comment]
I don't think we should use the computed properties to convert from`JSON.Number` to `Double`, `Int`, etc. Swift API Design Guidelines states that conversions should be done through Initializers. @czechboy0 I'm not sure if they should be public.

**Comment by paulofaria** [comment]
Also, we need tests for those conversions.

**Comment by paulofaria** [comment]
How do the computed properties and the initializers that are already there differ?

**Comment by loganwright** [comment]
@czechboy0 yea, no problem. I just wasn't sure if everyone defined them the same way w/ optionality etc. It might be best to leave convenience to individual libs, but if we all like the implementation, we can share it

**Comment by loganwright** [comment]
I'd mostly like to avoid defining JSON convenience, because some libraries prefer `var int: Int` for example to be non-optional and check `number.int ?? Int(string) ?? 0` or something.

For JSON.Number specifically, I think the definitions are fairly obvious. I'd prefer `var double: Double` to also check against Double.max if possible and be optional as well.

**Comment by czechboy0** [comment]
@paulofaria The computed properties do more checking before the conversions, the initializers might actually produce incorrect results now that I'm looking at them (like pasing Number(Double(2.1)) into the Int initializer will produce 2, won't it?)

**Comment by czechboy0** [comment]
@LoganWright Yeah that sounds right, let's keep them private.

**Comment by paulofaria** [comment]
Yeah it's a lossy conversion that only protects from overflows. There are comments about a swift standard library proposal for failable initializers that protect from overflow.

**Comment by paulofaria** [comment]
Just saw it got accepted

https://bugs.swift.org/browse/SR-1491
https://github.com/apple/swift-evolution/blob/master/proposals/0080-failable-numeric-initializers.md

**Comment by paulofaria** [comment]
Hmm looks like the proposal is for lossless conversions.

> This proposal is to add a new family of conversion initializers to all numeric types that either complete successfully without loss of information or return nil.

**Comment by czechboy0** [comment]
@paulofaria That's very good news, at least we don't have to write our own and we can still guarantee correctness.

**Comment by czechboy0** [comment]
But in the meantime I think this is good enough. Let's wait for some more feedback, but I hope it won't sit here for ages 😆

**Comment by paulofaria** [comment]
I think we need some tests here. Actually, in general we need more tests. When I get some time I'll add some tests myself, but in the meantime can you add some here, please? I think we need a policy for test coverage. The sad thing is that SwiftPM test coverage is still not working. 😞

**Comment by tanner0101** [comment]
Delaying this another week to accumulate more upvotes on the PR comment.

**Comment by paulofaria** [comment]
@czechboy0 is this good to merge?

**Pull request closed without merging**
