### PR TITLE
add structured data

### PR DESCRIPTION
**Pull request by tanner0101**
Almost every project that uses `Data` will require a higher level of abstraction for this data; whether it be database storage, content negotiation, or otherwise. 

`StructuredData` introduces an abstraction for representing data that can be as simple as a single `null` value to as complex as a multi-tiered JSON tree. 

Uses:
- Content Negotiation: structured data is incredibly useful for content negotiation. Parsers can read interchange formats directly into structured data which can then be mapped onto data types. The same goes for serialization.
- Database: storing and fetching data from databases like mongo or SQL have value types that could be contained as structured data. 
- More... 

By add a structured data abstraction to `C7`, we can promote cross project interoperability with more than just the current structureless `Data`. This could greatly decrease boilerplate code and potentially improve performance for common tasks like parsing and serializing JSON, or passing data between modules.

Add a 👍 if you support this PR, or recommend a different solution / create a better PR and give that a 👍.

### CODE REVIEW

**Comment by Danappelxx** [comment]
I'm very much for this overall. However, I noticed that you removed the `Value` suffix from all of the cases (as compared to [here](https://github.com/Zewo/StructuredData/blob/master/Sources/StructuredData.swift#L28)). Can we discuss this? By renaming `arrayValue([StructuredData])` to just `array([StructuredData])`, you make it a compiler error to have an `array: [StructuredData]?` property (instead forcing alternative naming such as `arrayValue: [StructuredData]`).

Edit: Looks like I was mistaken, it actually does not lead to any naming conflicts (though I could swear that it did at some point). LGTM

**Comment by loganwright** [comment]
@Danappelxx it definitely used to, I believe it was resolved by the proposal that requires leading `.` on enum types. You could also specify `self.array` before it was fixed.

**Comment by dreymonde** [comment]
I think we should reconsider our «no convenience in OpenSwift» policy. I don’t see any good in a bunch of conflicting libraries only goal of which is to make C7 code usable. It would introduce so much inconsistency.

**Comment by dreymonde** [comment]
upd: I meant we should add some convenient methods to `StructuredData` and not rely so heavily on some other higher-level libraries.

**Comment by tanner0101** [comment]
@dreymonde You can create a PR into this one that adds more convenience methods. Though I would prefer to keep it light and add things if and when we find they are absolutely necessary.

**Comment by paulofaria** [comment]
Related to https://github.com/open-swift/docs/issues/9

**Comment by tanner0101** [comment]
Merging this since we have 5 votes.

**Pull request merged**
