### PR TITLE
add Number

### PR DESCRIPTION
**Pull request by paulofaria**
This adds the new type `Number` which is an abstraction for a number. It abstracts the storage size and provides a Swifty way to convert to and from `Number` to any native number in Swift.

``` swift
let number = Number(2)
number.isStoredAsDouble // false
number.isStoredAsInt // true
let double = Double(number)
let float: Float = 1.5
let floatNumber = Number(float)
```

`Number` is as basic as `Data` and having it here wouldn't be **forcing** people to use it. It would be **allowing** other projects to have an abstraction for numbers.

### CODE REVIEW

**Comment by paulofaria** [comment]
Later I'll add the literal convertibles.

**Comment by loganwright** [comment]
I don't that this is necessary and should be included in C7. We don't need a further abstraction of numbers for C7 to function which I think conflicts with.

> minimum viable code required for interop.

I'm concerned that OpenSwift is becoming a convenience bag for things that individuals might want, rather than it's original intent of facilitating better communication between Swift projects in the most minimum way possible. 

A good standard doesn't impose, it guides.

**Comment by paulofaria** [comment]
Most high-level type-safe languages have an abstraction for `Number` that is used in countless kinds of applications. I think saying that this proposal is only good for an individual is a bit of a stretch.

**Comment by dreymonde** [comment]
I don’t like this idea, because it looks like we’re trying to «improve» Swift standard library, and that is no good. I assume there is the reason of _not_ having `Number` type in Swift. I don’t think we should mold Swift experience in any way — as @LoganWright mentioned, that is not our goal. `Number` inside of `JSON` is fine — but `Number` to be used wider is overly.

**Comment by paulofaria** [comment]
> I think we should reconsider our «no convenience in OpenSwift» policy. I don’t see any good in a bunch of conflicting libraries only goal of which is to make C7 code usable. It would introduce so much inconsistency.
> @dreymonde 

Why the contradiction? On that PR you're pro convenience and here you're not.

**Comment by dreymonde** [comment]
@paulofaria we’re talking about different things. I assume that you didn’t understand me correctly. On that PR (#37) I support the idea of adding convenience initializers and so on to `StructuredData`, so it would look more like a Zewo’s `StructuredData`, not the «bare bones».

**Comment by paulofaria** [comment]
Looks like you're all trying to make `JSON` weak and `StructuredData` strong, when it's completely unnecessary. They solve different problems. We shouldn't give special treatment for the proposals based on personal taste. I said before I prefer `StructuredData` when you have to handle more than one data type. But when you know you'll only handle `JSON`, it should be a good experience as it is with `StrucutedData`.

**Comment by dreymonde** [comment]
@paulofaria I wasn’t talking about `JSON`, `StructuredData` or anything in particular, I was talking in general. If we add `JSON` I too suggest us not to leave just the plain `enum`, but add some useful methods too. Anyway, this has absolutely nothing to do with `Number`, so I don’t understand why we’re discussing it here.

**Comment by paulofaria** [comment]
Well `Number` would be a convenience that, yeah, Swift doesn't provide. But if you're suggesting that Open Swift should stop being a set of standard protocols and become more like a standard library (having convenience stuff), we will be doing what Swift's standard library should be doing (or what the standard library of other languages does). In other words, if you propose Open Swift should become a standard library, I can't understand why you would say that we shouldn't have `Number`.

**Comment by dreymonde** [comment]
You’re overdramatizing my words. If you say that Swift needs `Number` type, I suggest it’s better to propose that in swift-evolution. I see OpenSwift not as stdlib extension, but as a starting point to inter-library communication. `JSON` is appropriate here because libraries need it and cannot connect with each other, because they’re using their own interpretations of JSON, in most cases — quite similar interpretations. Same with `Data`, `Stream`, `URI`, `Request` and so on. But `Number`? I personally don’t see a need in `Number` here. I like @czechboy0 approach with `Number` inside of `JSON` — because it’s a tiny implementation detail of `JSON`. But `Number` on its own is obtrusion. Do we want developers to use `Number` in their code everywhere, instead of `Int` and `Double`? Well, that’s `NSNumber`, and there is a reason why it was left behind by Swift core team. And I don’t see why we should «fix» that.

**Comment by paulofaria** [comment]
> there is a reason why it was left behind by Swift core team

Yeah, and there is no `Data` on Swift's standard library, for a reason. So this means we shouldn't have `Data` here? `Data` is as basic as `Number`. My point is that the arguments you're using are selective.

I never said people should use `Number` instead of `Int` and `Double` everywhere. Or that people should use `JSON` over `StructuredData`. We can't force people to do anything. But what we should do is **allow**. And it looks like you're all putting more energy on things you think are best for the use cases you're focusing and blocking everything that is not related to it. Like, @czechboy0 proposed `JSON` and all of the sudden a `StructuredData` PR appears. Yeah, I know we all talked about `StructuredData` at `C7` before. But my point is that everybody is more interested in `StructuredData` than `JSON`, and so it looks like you're trying to weaken `JSON` and make `StructuredData` stronger. And that's completely unnecessary. The use cases are completely different. I really can't see why you want to make `C7` more restrictive when it should **allow** more freedom. Having `Number` is not **forcing** anyone to use it. It is **allowing** people to use share it between their projects. Talking specifically about one use case of `Number`. Having `JSON` use number **allows** more freedom. It **allows** one to create a parser/serializer that keeps the format used in the input when creating the output. 

`Number` is supposed to be used in specific use cases where you just want a number abstraction and you don't care about the storage type. This is perfect for `JSON` and a number of other applications. And if people need it they will have to create their own. Just like people used to do with `Data`. So why not have a standard type for that?

**Comment by dreymonde** [comment]
@paulofaria faithfully, this discussion doesn’t have to do anything with `JSON` or `StructuredData`, really. I’m talking about `Number`. I **understand** the need of `Number` for `JSON`, for example, and I’m not arguing with that. But having it just floating around is not a good idea. Maybe we should create new repo with `JSON`, `XML`, `YAML` and whatever (maybe even `StructuredData`), and we should put `Number` there, so the usage scenario will be clear.

**Comment by paulofaria** [comment]
`Number` is useful and people are free to use it or not. I don't see why it would be bad to have it here. If you don't need it, don't use it. This is by no means an imposition. We absolutely can't enforce another library to use a type. It's impossible. So It would be nothing like **forcing**, it would be **allowing**. And I really can't see how this could be bad.

**Comment by tanner0101** [comment]
I think we should focus on strengthening the original PR comment for the community to vote rather than trying to provide counter points in the comments. This is turning into a bit of a tl;dr.

**Comment by paulofaria** [comment]
I agree @tannernelson. But with discussion also comes enlightenment. I, for example, thought that losing the formatting between parsing/serializing could be a problem. I don't think it is now. I'm not 100% sure yet. But, the point is that discussing I opened up my mind. Anyway, I'll update the first comments.

**Comment by dreymonde** [comment]
@paulofaria there’s two different philosophies:
1) «We’re not forcing, we’re allowing»
2) «We’re standard library, so we should include only things that are clear and necessary, because something excess will raise misunderstanding»

I’m not saying that only one of these is correct. But we should choose.

**Comment by paulofaria** [comment]
> We’re **standard library**

What? [Freudian slip](https://en.wikipedia.org/wiki/Freudian_slip)? haha. Anyway, we could not have `Number` as a separate type and cram it inside `JSON`, for sure. But if we found a use for it with `JSON` and we all know it can be used in other use cases, why hide it? Why fear it? What misunderstanding could it cause?

**Comment by dreymonde** [comment]
@paulofaria well, we’re standard library at some point. Or «library of standards», if one wishes.
I think my final point is https://github.com/open-swift/C7/pull/34#issuecomment-220035336. For me it seems like the most balanced option. I can’t see any other not-bad-practice way of using `Number` instead of `Int`/`Double` outside of JSON/XML/so on.

**Comment by paulofaria** [comment]
> **not-bad-practice** way of using `Number`

Can you give me one bad practice way of using `Number`? Or more, actually, haha. I'm having a hard time understanding this argument.

**Comment by dreymonde** [comment]
@paulofaria today is the «I can’t say things so others will understand me correctly»-day for me 😄 
Well, I’ll answer to a question with a question: what are the other usages for `Number` outside of representing a number for interchanging?

And the bad practices are simply:

``` swift
struct Counter: {
    var count: Number
}
// —
struct Rect {
    var height: Number
    var width: Number
}
```

Or anything like that. And I can see a situation where one decided to put `Number` in his business logic — that’s what I mean by «bad practice». Or at least it seems to me like a bad practice, maybe I’m wrong.

**Comment by czechboy0** [comment]
@dreymonde
- `Number` is an abstraction used widely in high level languages for decades.
- People will use it in appropriate situations, like any other API, and I trust they know better when they need it than we do.
- I don't think it's the job of open swift to prohibit people from using such time-tested API, or call it a "bad practice", which is just an opinion (and open swift has "unopinionated" in its principles).

I'm for adding Number as a type, I think it's a great way to abstract away the storage characteristics of a number, without losing precision (or actually generating the wrong result) by casting it. I think it's absolutely appropriate to scrutinize the details of how it works, but I don't see why it shouldn't be added in principle, as it's a very useful API (judging not by my opinion, but by looking into many other popular languages). I propose to accept the base type as is, and then create PRs with modifications, if needed, so that discussion is always focused on concrete technical details.

**Comment by dreymonde** [comment]
@czechboy0 

> Number is an abstraction used widely in high level languages for decades.
> …
> (judging not by my opinion, but by looking into many other popular languages)

This is understandable. However `Number` is not used by Swift itself, not used for a reason. I assume that is my biggest complaint about this PR. However, that’s all I wanted to say. The final decision will be made at «merge day», I think?

**Comment by paulofaria** [comment]
With Swift's standard library you can write:

``` swift
let counter: Double = 0
```

This is clearly a use case that an `Int` would be best suited. But what did Swift team do about it? Did they remove `Double` so one can't use it when it's not appropriate? No, they just did nothing about it. If they removed it. The people would have to figure out a way to represent decimals with `Int`. Sure it would work. But it wouldn't be as good as having `Double`. And the opposite can happen as well. 

``` swift
let heightSignificand: Int = 634
let heightExponent: Int = -2
```

So Swift removed `Int` so people can only use `Double` for this use case? Nope. There are different types for different purposes, but people can do whatever they want and we can't control that. And I would say even more. Even if one wants to use `Number` for everything; It's their decision. We can't prevent people that will make good use of `Number` because some will make bad use.

**Comment by paulofaria** [comment]
@dreymonde Swift doesn't have `Data` for a reason. And still we have `Data` here. And `Number` should be here for the same reason `Data` is here. To **allow** people to use the same abstraction in different projects.

**Comment by tanner0101** [comment]
@paulofaria would you like to keep this open for another week to consider merging or should we close it?

**Comment by czechboy0** [comment]
I'm still for this PR, it nicely abstracts away the storage properties of numbers without losing precision by actually _storing_ it in just one format. The previous discussion was not really about the technical merits of the PR, so I'd encourage everyone who actually thinks this is a bad idea _for a specific reason_ (arguments like "I don't need it" don't really help here) to comment, so that we can have a fruitful discussion.

It has thumbs up and there are people who would like to use it, plus it's an abstraction present in many other high level languages (i.e. it's not a crazy new concept). So I'd love to hear any opposition (if there still is any) that goes to the point. Otherwise I don't see why this shouldn't get merged in the next cycle.

**Comment by tanner0101** [comment]
Merging this with 4 upvotes.

**Pull request merged**
