### PR TITLE
Files

### PR DESCRIPTION
**Pull request by Joannis**
I think having a `File` protocol is essential. For example it'd allow a dev to take a File from GridFS (MongoDB) and directly output it in the browser like you would with a profile picture.

The reason for a protocol is that a file struct would copy huge amount of data all the time. And a class would be referencing a file even though you want to copy it for editing. So this way we'll have both options without having two types of files.

Alternatively we could have a file struct and create a container around that... so let's discuss!

### CODE REVIEW

**Comment by paulofaria** [comment]
What are the informations you need from the file? I don't think a `File` should have `data` property. I think the best abstraction for files would be something like a stream, where you can read and write binary data to. In most scenarios a stream itself would be enough.

**Comment by paulofaria** [comment]
The problem would then be the metadata associated with the `File`. Also, I really don't think we should `import Foundation`.

**Comment by tanner0101** [comment]
S4 needs to remain Foundation free.

**Comment by paulofaria** [comment]
What about this:

```
protocol File: Stream {
    var path: String { get }
}
```

**Comment by paulofaria** [comment]
we could even add initializers

**Pull request closed without merging**
